version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: "-"
    groups:
      all-dependencies:
        patterns:
          - "*"
    assignees:
      - "username here" # Assigns the pull request to your GitHub username
    labels:
      - "dependencies" # Adds a "dependencies" label to the pull requests
