version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "username here" # Assigns the pull request to your GitHub username
    labels:
      - "dependencies" # Adds a "dependencies" label to the pull requests